defaults:
  - _self_
  - network: ${oc.env:DATA_VARIANT}/${oc.env:METHOD_VARIANT}/default # environmental variables can be used to parameterize configs
  - dataloader: ${oc.env:DATA_VARIANT}
  - logger: wandb/default
  - metric: all_test
  - hydra: default
  - fabric: default

exp:
  seed: 42
  log_dir: # set during runtime to automatically created dir
  run_func: 
    _target_: experiment.test.run